//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDays2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalServiceState
    {
        public RentalServiceState()
        {
            this.RentalServices = new HashSet<RentalService>();
        }
    
        public int RentalServiceStateID { get; set; }
        public string RentalServiceStateName { get; set; }
    
        public virtual ICollection<RentalService> RentalServices { get; set; }
    }
}
