//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDays2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.RentalServices = new HashSet<RentalService>();
        }
    
        public int ResourceID { get; set; }
        public short LocationID { get; set; }
        public string RessourceName { get; set; }
        public string SSNo { get; set; }
        public Nullable<short> MachineTypeID { get; set; }
        public string Status { get; set; }
        public string SerialNo { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MachineType MachineType { get; set; }
        public virtual ICollection<RentalService> RentalServices { get; set; }
    }
}
