//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSQL2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpOrder
    {
        public int empid { get; set; }
        public Nullable<System.DateTime> ordermonth { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> val { get; set; }
        public Nullable<int> numorders { get; set; }
    }
}
