//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSQL2015
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails1
    {
        public int orderid { get; set; }
        public int productid { get; set; }
        public decimal unitprice { get; set; }
        public short qty { get; set; }
        public decimal discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Orders1 Orders1 { get; set; }
    }
}
